#####-----后摄推理设备-----#####
device: "NPU"

#####-----后摄硬件与基础参数-----#####
camera_name: "hikrobot"
serial_number: "00DA5751514"
vid_pid: "2bdf:0001"
exposure_ms: 5
gain: 12
image_width: 1440
image_height: 1080
fps: 40

#####-----后摄标定参数-----#####
camera_matrix: [1810.18913, 0.0, 729.08455, 0.0, 1811.24101, 546.01958, 0.0, 0.0, 1.0]
distort_coeffs: [-0.054302, -0.016375, 0.000738, -0.000240, 0.0]
R_camera2gimbal: [1, 0, 0, 0, 1, 0, 0, 0, 1]
t_camera2gimbal: [0.0, 0.0, 0.0]
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]